# Generated by Django 2.1.7 on 2019-07-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('rule', models.TextField(verbose_name='规则')),
                ('request_body', models.TextField(verbose_name='请求')),
                ('response_body', models.TextField(verbose_name='响应')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '历史记录',
                'verbose_name_plural': '历史记录',
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='RuleInfo',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='UID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('request_body', models.TextField(verbose_name='请求')),
                ('response_body', models.TextField(verbose_name='响应')),
                ('proxy', models.CharField(max_length=20, verbose_name='转发代理')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则',
                'db_table': 'rule',
            },
        ),
    ]
