# Generated by Django 2.1.7 on 2019-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='ruleinfo',
            name='uid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
    ]
